POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blogi Testitietokantaan",
  "author": "D K",
  "url": "https://www",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Dan Kor",
  "url": "http://www.toimivaosoite.fi/",
  "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog post without likes",
  "author": "So Sad",
  "url": "http://iwantlikesGimmeSomeLikes.com/"
}